spring:
  application:
    name: innowise-user-service


  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/innowise_user_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

user:
  card:
    max-limit: 5

cache:
  ttl:
    user: 10m
    card: 10m
    cards: 5m